[package]
name = "port-sniffer"
version = "0.1.0"
authors = ["joesan <secret@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.9"
serde_derive = "1.0.91"
serde = "^1.0.8"
chrono = { version = "0.4", features = ["serde"] }
